# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pongsakorn Semsuwan
tagline:          'Newbie programmer'
description:      'Hi there! I''m a newbie programmer living in Thailand. Been coding Java for a few years and currently working on learning Javascript and Node.js.'
url:              http://pongsakornsemsuwan.github.io
baseurl:          /

author:
  name:           'Pongsakorn Semsuwan'
  url:            https://twitter.com/pongsakornsemsuwan

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pongsakornsemsuwan

facebookurl:         https://www.facebook.com/pongsakorn.semsuwan

gems: [jekyll-paginate]
