# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pongsakorn Semsuwan
tagline:          'Newbie programmer'
description:      'Hi there! I'm a newbie programmer living in Thailand. Been working on Java for a few years and currently working on learning Javascript and Node.js.'
url:              http://pongsakornsemsuwan.github.io
baseurl:          /

author:
  name:           'Pongsakorn Semsuwan'
  url:            https://twitter.com/pongsakornsemsuwan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pongsakornsemsuwan

facebookurl:         https://www.facebook.com/pongsakorn.semsuwan
