# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pongsakorn Semsuwan
tagline:          'Newbie programmer'
description:      'Newbie programmer.'
url:              http://pongsakornsemsuwan.github.io
baseurl:          /

author:
  name:           'Pongsakorn Semsuwan'
  url:            https://twitter.com/pongsakornsemsuwan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
